#!/bin/bash -eu

npm install -g npm@^6.4.1
npm -v

if [ ${TEST_SUITE} == "standard" ]; then
	echo '[medic] skipping grunt'
	exit 0
fi

npm install -g grunt-cli
npm ci
npm ls || true
node --version
npm --version
cd shared-libs/phone-number && npm install && cd ../..
cd webapp && rm package-lock.json && npm install && cd ..
node --stack_size=10000 `which grunt` ci-build
